# Generated by Django 6.1.1 on 2026-10-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
