# Generated by Django 6.1.1 on 2026-10-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Наприклад: АА, КА, ТА, ТТ",
                        max_length=20,
                        unique=True,
                        verbose_name="Коди регіону",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Назва області / міста"
                    ),
                ),
            ],
            options={
                "verbose_name": "Регіон",
                "verbose_name_plural": "Регіони",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        db_index=True,
                        help_text="Наприклад: AA1234BB",
                        max_length=20,
                        unique=True,
                        verbose_name="Держ. номер",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Марка (Vendor)"
                    ),
                ),
                ("model", models.CharField(max_length=50, verbose_name="Модель")),
                ("year_from", models.PositiveIntegerField(verbose_name="Рік випуску")),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("petrol", "Бензин"),
                            ("diesel", "Дизель"),
                            ("electric", "Електро"),
                            ("hybrid", "Гібрид"),
                            ("lpg", "Газ (ГБО)"),
                        ],
                        default="petrol",
                        max_length=20,
                        verbose_name="Тип пального",
                    ),
                ),
                (
                    "engine_volume",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Наприклад: 2.0, 3.5",
                        max_digits=3,
                        verbose_name="Об'єм двигуна (л)",
                    ),
                ),
                ("color", models.CharField(max_length=30, verbose_name="Колір")),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("sedan", "Седан"),
                            ("hatchback", "Хетчбек"),
                            ("suv", "Позашляховик / Кросовер"),
                            ("wagon", "Універсал"),
                            ("coupe", "Купе"),
                            ("minivan", "Мінівен"),
                        ],
                        default="sedan",
                        max_length=30,
                        verbose_name="Тип кузова",
                    ),
                ),
                ("registration_date", models.DateField(verbose_name="Дата реєстрації")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата додавання"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="vehicles.region",
                        verbose_name="Регіон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобіль",
                "verbose_name_plural": "Автомобілі",
                "ordering": ["-created_at"],
            },
        ),
    ]
