# Generated by Django 6.1.1 on 2026-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="Коди регіону"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="engine_volume",
            field=models.DecimalField(
                decimal_places=1, max_digits=3, verbose_name="Об'єм двигуна (л)"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="Держ. номер"
            ),
        ),
    ]
