# Generated by Django 6.1.1 on 2026-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_region_code_alter_vehicle_engine_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="Об'єм двигуна (л)"),
        ),
    ]
